### PR TITLE
Remove upper version constraint on OpenSSL

### PR DESCRIPTION
**Pull request by stanhu**
This change is needed for openssl to work in Ruby 3.2.0 without downgrading the version since Ruby 3.2.0 ships with the openssl 3.1 by default.

### CODE REVIEW

**Review by santiagorodriguez96 — APPROVED** [review]
LGTM 💯 

Thank you!!! 🙌

**Comment by bdewater** [comment]
@santiagorodriguez96 I can't merge in this repo either 😅

**Comment by stanhu** [comment]
@santiagorodriguez96 Thanks for the merge! Do you think you could release this gem as well as https://github.com/cedarcode/openssl-signature_algorithm so that we can begin the process of updating `webauthn` and other dependencies?

**Comment by santiagorodriguez96** [comment]
> @santiagorodriguez96 Thanks for the merge! Do you think you could release this gem as well as https://github.com/cedarcode/openssl-signature_algorithm so that we can begin the process of updating `webauthn` and other dependencies?

For sure! We will do it asap 🙂

**Pull request merged**
